### PR TITLE
Added README.md file to the project

### PR DESCRIPTION
**Pull request by RDCH106**
Generated a README.md for Pokemon 3D project.

Maybe it would be usefull the generation of a wiki with information about how to configure the develop environment, the engine design, examples...

I am working on it: [https://github.com/RDCH106/Pokemon3D/wiki](https://github.com/RDCH106/Pokemon3D/wiki)

### CODE REVIEW

**Comment by trommlbomml** [comment]
Thank you for your effort so far. I think it is not a bad idea writing this.

We don't use XNA but MonoGame 3.4. Furthermore, we currently have a branch for using Nuget to reference thirdparty-assemblies, which will merged in the next days. This could be reflected by the wiki too.

**Comment by RDCH106** [comment]
Ok

When you want, accept the changes for the Readme.

To talk about the wiki content, where will be the better place to do it? Maybe in the forum of the game, other comunication channel...? I am very interesting to help in the engine develop.

**Comment by trommlbomml** [comment]
Thank you very much for your intereset. I think some support would be ok if you are interested, but Nilllzz, the founder, needs also to accept this.

**Comment by Fallenleader** [comment]
I was actually gonna mention this as an "issue", but you beat me to it :P
Off topic, but where is the structure for the pokemon themselves? It would really help my project to see how Pokemon3D addressed this. Unity is very much a different approach, but seeing how pokemon is generated and stored would be very useful. I am having difficulty creating the structure for my game. the rest of the code is fine though.

**Comment by Aragas** [comment]
@Fallenleader wiki's like bulbapedia has this kind of info

**Comment by trommlbomml** [comment]
I created a wiki for this game regarding architecture. The readme.md tells to read the wiki of this repository for more information. This way I would like to close the PR.

**Pull request closed without merging**
